### ISSUE TITLE
choosing desired channel

### ISSUE THREAD

**Issue by beetle060** [markspit93/AutoTechno#4]
Hi, 

i got markspit93's Auto Techno modified to my channels, added my listenkey and finally managed to build Auto Techno. I love to be able listening DI.FM on Android Auto without hassle again.

So, thank you for this little gem!

on Auto Techno when i tap the "burger" icon, i get a list of my favorites. Shouldn't i be able to choose from there? It does not work for me. I can only skip forth and back on the main menu.

In case this is a bug, could you have a look at it? 
In case this feature is missing, please log this as a feature request.

Anyway, thanks for this code, i'd have paid for this. Consider adding an "enter listenkey" feature, add all DI.FM channels and charge some money for it.

Cheers,
Stefan Niestegge

**Comment by markspit93** [comment]
Hi there!

I will check the Favorites behavior since it should act as you described.
Regarding money, I think it would not be exactly legal to make profit off DI.FM's service so it will stay free for whomever finds it.

**Comment by markspit93** [comment]
Sorry for the delay!

The favorites bug you experienced should be fixed with the latest commit.
